// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlojPodataka.TehnoloskeKlase;

#nullable disable

namespace SlojPodataka.Migrations
{
    [DbContext(typeof(TurnirDbContext))]
    partial class TurnirDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Igrac", b =>
                {
                    b.Property<int>("IgracID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IgracID"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ELO")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Klub")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IgracID");

                    b.ToTable("Igrac", (string)null);
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikID"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("KorisnikID");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.PlasmanIgraca", b =>
                {
                    b.Property<int>("PlasmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlasmanID"));

                    b.Property<decimal>("Bodovi")
                        .HasColumnType("decimal(4,1)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<int>("IgracID")
                        .HasColumnType("int");

                    b.Property<int>("Mesto")
                        .HasColumnType("int");

                    b.Property<decimal>("Nagrada")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TurnirID")
                        .HasColumnType("int");

                    b.HasKey("PlasmanID");

                    b.HasIndex("IgracID");

                    b.HasIndex("TurnirID");

                    b.ToTable("PlasmanIgraca", (string)null);
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Turnir", b =>
                {
                    b.Property<int>("TurnirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnirID"));

                    b.Property<int>("BrojRundi")
                        .HasColumnType("int");

                    b.Property<int>("BrojUcesnika")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormatTakmicenja")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GlavniArbitar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NagradniFond")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NazivTurnira")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Organizator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TiebreakKriterijum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipTurnira")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VremenskaKontrola")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TurnirID");

                    b.ToTable("Turnir", (string)null);
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.PlasmanIgraca", b =>
                {
                    b.HasOne("SlojPodataka.KlasePodataka.Igrac", "Igrac")
                        .WithMany("Plasmani")
                        .HasForeignKey("IgracID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SlojPodataka.KlasePodataka.Turnir", "Turnir")
                        .WithMany("Plasmani")
                        .HasForeignKey("TurnirID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Igrac");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Igrac", b =>
                {
                    b.Navigation("Plasmani");
                });

            modelBuilder.Entity("SlojPodataka.KlasePodataka.Turnir", b =>
                {
                    b.Navigation("Plasmani");
                });
#pragma warning restore 612, 618
        }
    }
}
